language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jstanley1730/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jstanley1730/docker-react npm run test